title: Wiki - The Internet of Things: A survey - Enabling Technologies.
description: Wiki sobre o tópico três do artigo "The Internet of Things: A survey".

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: https://matheussebastiani.github.io
baseurl: "/wiki-iot-a-survey"

color_scheme: dark

aux_links:
  "Repositório no GitHub":
    - "//github.com/matheussebastiani/wiki-iot-a-survey"
